[2024-08-22T16:22:02.729+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-22T16:22:02.820+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_dag.whole_spotify_etl scheduled__2024-08-21T00:20:00+00:00 [queued]>
[2024-08-22T16:22:02.889+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_dag.whole_spotify_etl scheduled__2024-08-21T00:20:00+00:00 [queued]>
[2024-08-22T16:22:02.891+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-22T16:22:03.032+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): whole_spotify_etl> on 2024-08-21 00:20:00+00:00
[2024-08-22T16:22:03.103+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-22T16:22:03.105+0000] {standard_task_runner.py:72} INFO - Started process 119 to run task
[2024-08-22T16:22:03.105+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spotify_dag', 'whole_spotify_etl', 'scheduled__2024-08-21T00:20:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/spotify_dag.py', '--cfg-path', '/tmp/tmp0jh3yjon']
[2024-08-22T16:22:03.106+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask whole_spotify_etl
[2024-08-22T16:22:03.542+0000] {task_command.py:467} INFO - Running <TaskInstance: spotify_dag.whole_spotify_etl scheduled__2024-08-21T00:20:00+00:00 [running]> on host faa894082a18
[2024-08-22T16:22:04.302+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='andresxmaldonado@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_dag' AIRFLOW_CTX_TASK_ID='whole_spotify_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T00:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-21T00:20:00+00:00'
[2024-08-22T16:22:04.303+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-22T16:22:04.311+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-22T16:22:04.311+0000] {logging_mixin.py:190} INFO - Current task name:whole_spotify_etl state:running start_date:2024-08-22 16:22:02.827508+00:00
[2024-08-22T16:22:04.312+0000] {logging_mixin.py:190} INFO - Dag name:spotify_dag and current dag run status:running
[2024-08-22T16:22:04.312+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-22T16:22:04.347+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/spotify_etl.py", line 180, in run_spotify_etl
    token = get_token()
            ^^^^^^^^^^^
  File "/opt/airflow/plugins/spotify_etl.py", line 25, in get_token
    auth_string = CLIENT_ID + ":" + CLIENT_SECRET
                  ^^^^^^^^^
NameError: name 'CLIENT_ID' is not defined
[2024-08-22T16:22:04.532+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-22T16:22:04.532+0000] {logging_mixin.py:190} INFO - Task start:2024-08-22 16:22:02.827508+00:00 end:2024-08-22 16:22:04.530257+00:00 duration:1.702749
[2024-08-22T16:22:04.543+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): whole_spotify_etl> dag:<DAG: spotify_dag> dagrun:<DagRun spotify_dag @ 2024-08-21 00:20:00+00:00: scheduled__2024-08-21T00:20:00+00:00, state:running, queued_at: 2024-08-22 16:21:51.436147+00:00. externally triggered: False>
[2024-08-22T16:22:04.543+0000] {logging_mixin.py:190} INFO - Failure caused by name 'CLIENT_ID' is not defined
[2024-08-22T16:22:04.544+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_dag, task_id=whole_spotify_etl, run_id=scheduled__2024-08-21T00:20:00+00:00, execution_date=20240821T002000, start_date=20240822T162202, end_date=20240822T162204
[2024-08-22T16:22:04.630+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:155: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-08-22T16:22:04.630+0000] {configuration.py:1058} WARNING - section/key [smtp/smtp_user] not found in config
[2024-08-22T16:22:04.631+0000] {email.py:272} INFO - Email alerting: attempt 1
[2024-08-22T16:22:04.662+0000] {configuration.py:1058} WARNING - section/key [smtp/smtp_user] not found in config
[2024-08-22T16:22:04.663+0000] {email.py:272} INFO - Email alerting: attempt 1
[2024-08-22T16:22:04.668+0000] {taskinstance.py:1234} ERROR - Failed to send email to: ['andresxmaldonado@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/spotify_etl.py", line 180, in run_spotify_etl
    token = get_token()
            ^^^^^^^^^^^
  File "/opt/airflow/plugins/spotify_etl.py", line 25, in get_token
    auth_string = CLIENT_ID + ":" + CLIENT_SECRET
                  ^^^^^^^^^
NameError: name 'CLIENT_ID' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1442, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 274, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 318, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 865, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 850, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1232, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3595, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1444, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 274, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 318, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 865, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 850, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-08-22T16:22:04.725+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-22T16:22:04.725+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task whole_spotify_etl (name 'CLIENT_ID' is not defined; 119)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/spotify_etl.py", line 180, in run_spotify_etl
    token = get_token()
            ^^^^^^^^^^^
  File "/opt/airflow/plugins/spotify_etl.py", line 25, in get_token
    auth_string = CLIENT_ID + ":" + CLIENT_SECRET
                  ^^^^^^^^^
NameError: name 'CLIENT_ID' is not defined
[2024-08-22T16:22:04.823+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-22T16:22:04.942+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-22T16:22:04.978+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-08-22T17:37:14.261+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-22T17:37:14.341+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_dag.whole_spotify_etl scheduled__2024-08-21T00:20:00+00:00 [queued]>
[2024-08-22T17:37:14.381+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_dag.whole_spotify_etl scheduled__2024-08-21T00:20:00+00:00 [queued]>
[2024-08-22T17:37:14.382+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-22T17:37:14.433+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): whole_spotify_etl> on 2024-08-21 00:20:00+00:00
[2024-08-22T17:37:14.465+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-22T17:37:14.470+0000] {standard_task_runner.py:72} INFO - Started process 123 to run task
[2024-08-22T17:37:14.480+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spotify_dag', 'whole_spotify_etl', 'scheduled__2024-08-21T00:20:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/spotify_dag.py', '--cfg-path', '/tmp/tmpkp47pil6']
[2024-08-22T17:37:14.481+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask whole_spotify_etl
[2024-08-22T17:37:14.738+0000] {task_command.py:467} INFO - Running <TaskInstance: spotify_dag.whole_spotify_etl scheduled__2024-08-21T00:20:00+00:00 [running]> on host 95d8e05632f7
[2024-08-22T17:37:15.158+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='andresxmaldonado@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_dag' AIRFLOW_CTX_TASK_ID='whole_spotify_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T00:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-21T00:20:00+00:00'
[2024-08-22T17:37:15.162+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-22T17:37:15.175+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-22T17:37:15.177+0000] {logging_mixin.py:190} INFO - Current task name:whole_spotify_etl state:running start_date:2024-08-22 17:37:14.347416+00:00
[2024-08-22T17:37:15.180+0000] {logging_mixin.py:190} INFO - Dag name:spotify_dag and current dag run status:running
[2024-08-22T17:37:15.183+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-22T17:37:16.845+0000] {logging_mixin.py:190} INFO - True
[2024-08-22T17:37:16.845+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-22T17:37:16.858+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-22T17:37:16.859+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=spotify_dag, task_id=whole_spotify_etl, run_id=scheduled__2024-08-21T00:20:00+00:00, execution_date=20240821T002000, start_date=20240822T173714, end_date=20240822T173716
[2024-08-22T17:37:16.878+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-08-22T17:37:16.878+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-08-22T17:37:16.878+0000] {logging_mixin.py:190} INFO - Dag name:spotify_dag queued_at:2024-08-22 17:37:04.673418+00:00
[2024-08-22T17:37:16.878+0000] {logging_mixin.py:190} INFO - Task hostname:95d8e05632f7 operator:PythonOperator
[2024-08-22T17:37:16.923+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-22T17:37:16.984+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-22T17:37:16.993+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
